### ISSUE TITLE
SQL syntax highlighting incorrectly escapes backslashes

### ISSUE THREAD

**Issue by LordAro** [chrisbra/vim-sqloracle-syntax#6]
Backslashes in SQL do not need escaping, such that `'\'` is a valid string. The syntax highlighting does not reflect this - continuing the string past the end instead

There's also a lack of `''` not being escaped - this is a valid way of representing `'`

Best thing i could find resembling the standard: https://web.archive.org/web/20150922065035/https://mariadb.com/kb/en/sql-99/character-string-literals/

(Copied from vim/vim#3062 )

**Comment by chrisbra** [comment]
Does that mean, we can remove the `skip` part? Do you have an example file available to test against?

**Comment by LordAro** [comment]
Oops, lost some markup when copying

No file, but things like `'foo '' bar'` should be a single string, and `'foobar\'` should actually have an end to it, which as far as I can tell does indeed mean you can remove the skip part, not that I understand the vim syntax.

**Comment by chrisbra** [comment]
okay thanks. I removed it and add a sample file. Let's see if someone complains
